name: Cut new staging branch from master

on: [push]
# on:
#  push:
#    # Sequence of patterns matched against refs/heads
#    branches:
#      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      if: github.ref == 'refs/heads/master' && success()
    - name: fetch all
      if: github.ref == 'refs/heads/master' && success()
      run: |
          echo "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin && git checkout master && git pull origin master && git branch -D staging && git checkout -b staging && git push -f github staging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        GITHUB_USER: $GITHUB_ACTOR
