name: CI

on: [push]
# on:
#  push:
#    # Sequence of patterns matched against refs/heads
#    branches:
#      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: fetch all
      run: |
          echo "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git fetch --all && git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
          git fetch origin && git checkout master && git pull origin master && git branch -D staging && git checkout -b staging && git push -f github staging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        GITHUB_USER: $GITHUB_ACTOR
