name: CI

on: [push]
# on:
#  push:
#    # Sequence of patterns matched against refs/heads
#    branches:
#      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: fetch all
      run: |
          echo "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git fetch --all && git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        GITHUB_USER: $GITHUB_ACTOR
    - name: Cutting new staging from master
      if: github.ref == 'refs/heads/master' && success()
      uses: srt32/git-actions@v0.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        GITHUB_USER: $GITHUB_ACTOR
      with:
        args: git fetch origin && git checkout master && git branch -D staging && git pull origin master && git checkout -b staging && git push -f origin staging
